# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Next.js build & copy to remote

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup nodejs and yarn (with cache)
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: install yarn dependencies
      run: yarn install --frozen-lockfile
    - name: build nextjs app
      run: yarn build
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        source: "next.config.js,node_modules,package.json,.next"
        target: "~/ci"
